name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Ruby version from gemspec
        id: ruby-version
        run: |
          RUBY_VERSION=$(ruby -e "
            spec = Gem::Specification.load('rails_excel_reporter.gemspec')
            puts spec.required_ruby_version.requirements.first.last.to_s
          ")
          echo "version=$RUBY_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.version }}
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github
